### PR TITLE
Added fabric server jars

### PR DESCRIPTION
**Pull request by ShadowThijs**
Let me know if there is any modifications left to be made, I added only the mainstream versions as they had a easy to find release date.

### CODE REVIEW

**Comment by ShadowThijs** [comment]
After adding Fabric I also added Forge, sad part is that the formatting is shit...

**Comment by sinnayuh** [comment]
Very nice

**Comment by ShadowThijs** [comment]
whooo

**Comment by stephendotgg** [comment]
> whooo

thanks for the feature mate. :)

**Comment by ShadowThijs** [comment]
> > whooo
> 
> 
> 
> thanks for the feature mate. :)

With pleasure 😃

**Pull request merged**
